horten:
  debug: true

camera:
  toGif:
    path: ""

  record: 
    path: "/camera/record/$t.png"


hss:
  port: 8765

mysql:
  path: /
  connection: 
    host:     localhost
    port:     8889
    user:     root
    password: root
    database: orbit2 
  columns:  [ "time", "number" ]
  table: state
  debug: false

osc:
  incoming: 9001
  outgoing: 9000
